version: "3.8"

services:
  mongo:
    build:
      context: .
      dockerfile: ./Dockerfile-mongo
      args:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network

  web:
    build: ./web
    ports:
      - "${WEB_PORT}:80"

networks:
  app-network:
    driver: bridge
